name: Scrapy Crawl

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Scrapy
      run: pip install Scrapy
      
    - name: Run Scrapy Crawl
      run: |
        cd weibo   # 更改为你的scrapy项目路径
        scrapy crawl search  # 更改为你的爬虫名字
        
    - name: Set up Git
      run: |
        git config --global user.name 'mamingsuper'
        git config --global user.email 'mamingsuper0719@163.com'

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Add crawled data"
        if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
        else
            git push https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        fi
