name: Scrapy Crawl

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Scrapy
      run: pip install Scrapy
      
    - name: Run Scrapy Crawl
      run: |
        cd weibo   # 更改为你的scrapy项目路径
        scrapy crawl search  # 更改为你的爬虫名字
